import type { ReactNode } from "react";
import type { LineItem, HealthDimension, AllocationSlice } from "../lib/dashboard";
import { STATUS_SCORE, HEALTH_STATUS_LABEL } from "../lib/dashboard";
import { formatSgd } from "../lib/cpf";
import "./dashboard-export.css";

// Everything this component renders comes from data the user already typed into the
// Retirement Calculator on this device — nothing extra is collected just for this image,
// and generating the image happens entirely in the browser (html2canvas), never a server.

export interface HdbOverviewData {
  saleValue: number;
  cpfPrincipalUsed: number;
  cpfAccruedInterest: number;
  cpfRefund: number;
  loanOutstanding: number;
}

export interface RightsizingExportData {
  saleProceeds: number;
  cpfRefund: number;
  balanceAfterCpfRefund: number;
  replacementFlatPrice: number;
  legalMovingCosts: number;
  cashReleased: number;
}

export interface FinancialPositionAfterData {
  cpfSavings: number;
  investmentsAndInsurance: number;
  cashReleased: number;
  estimatedFinancialAssets: number;
}

export interface TimelineStepData {
  age: string;
  icon: string;
  label: string;
}

export interface DashboardExportData {
  generatedOn: string;
  currentAge: number;
  retirementAge: number;
  yearsToRetirement: number;
  monthlyIncome: number;
  monthlySurplus: number;
  onTrack: boolean;

  netWorth: number;
  hdbValue: number;
  totalCpf: number;
  totalInvestments: number;
  slices: AllocationSlice[];

  cpfOa: number;
  cpfMa: number;
  cpfSaRa: number;

  incomeItems: LineItem[];
  totalIncome: number;
  totalExpenses: number;
  totalLiabilities: number;

  investmentItems: LineItem[];
  expenseItems: LineItem[];
  liabilityItems: LineItem[];

  hdbOverview: HdbOverviewData | null;
  rightsizing: RightsizingExportData | null;
  financialPositionAfter: FinancialPositionAfterData | null;

  healthDimensions: HealthDimension[];
  overallScore: number;

  timelineSteps: TimelineStepData[];
}

const SLICE_COLORS: Record<AllocationSlice["key"], string> = {
  hdb: "#2a5da8",
  cpf: "#1f8a4c",
  investments: "#7a4fc9",
};

const STATUS_DOT: Record<HealthDimension["status"], string> = {
  strong: "#0ca30c",
  good: "#4c9a2a",
  moderate: "#fab219",
  attention: "#d03b3b",
};

function scoreColor(score: number): string {
  if (score >= 70) return "#0ca30c";
  if (score >= 40) return "#fab219";
  return "#d03b3b";
}

// An SVG stroke-based ring, not CSS conic-gradient() — html2canvas doesn't reliably
// render conic-gradient, but plain SVG shapes capture correctly.
function Donut({ slices, size = 110, strokeWidth = 16 }: { slices: AllocationSlice[]; size?: number; strokeWidth?: number }) {
  const r = (size - strokeWidth) / 2;
  const c = 2 * Math.PI * r;
  let offset = 0;
  return (
    <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`}>
      <circle cx={size / 2} cy={size / 2} r={r} fill="none" stroke="#eae5df" strokeWidth={strokeWidth} />
      {slices
        .filter((s) => s.pct > 0)
        .map((s) => {
          const dash = (s.pct / 100) * c;
          const el = (
            <circle
              key={s.key}
              cx={size / 2}
              cy={size / 2}
              r={r}
              fill="none"
              stroke={SLICE_COLORS[s.key]}
              strokeWidth={strokeWidth}
              strokeDasharray={`${dash} ${c - dash}`}
              strokeDashoffset={-offset}
              transform={`rotate(-90 ${size / 2} ${size / 2})`}
            />
          );
          offset += dash;
          return el;
        })}
    </svg>
  );
}

function Row({ label, value, bold, muted }: { label: string; value: string; bold?: boolean; muted?: boolean }) {
  return (
    <div className={`dex-row${bold ? " dex-row-bold" : ""}${muted ? " dex-row-muted" : ""}`}>
      <span>{label}</span>
      <span>{value}</span>
    </div>
  );
}

function Card({ title, icon, children }: { title: string; icon?: string; children: ReactNode }) {
  return (
    <div className="dex-card">
      <h3>
        {icon && <span className="dex-card-icon">{icon}</span>}
        {title}
      </h3>
      {children}
    </div>
  );
}

export function RetirementDashboardExportCard({ data }: { data: DashboardExportData }) {
  const strongPoints = data.healthDimensions.filter((d) => d.status === "strong" || d.status === "good").slice(0, 4);
  const actionPoints = data.healthDimensions.filter((d) => d.status === "moderate" || d.status === "attention").slice(0, 4);

  return (
    <div className="dex-root">
      <header className="dex-header">
        <div className="dex-header-title">
          <h1>🇸🇬 YOUR RETIREMENT DASHBOARD</h1>
          <p>Generated by SG Money — as at {data.generatedOn}</p>
        </div>
        <div className="dex-stats">
          <div className="dex-stat">
            <span className="dex-stat-label">Current age</span>
            <span className="dex-stat-value">{data.currentAge}</span>
          </div>
          <div className="dex-stat">
            <span className="dex-stat-label">Target retirement</span>
            <span className="dex-stat-value">{data.retirementAge}</span>
          </div>
          <div className="dex-stat">
            <span className="dex-stat-label">Years to go</span>
            <span className="dex-stat-value">{data.yearsToRetirement}</span>
          </div>
          <div className="dex-stat">
            <span className="dex-stat-label">Monthly income</span>
            <span className="dex-stat-value dex-positive">{formatSgd(data.monthlyIncome)}</span>
          </div>
          <div className="dex-stat">
            <span className="dex-stat-label">Monthly surplus</span>
            <span className={`dex-stat-value ${data.monthlySurplus >= 0 ? "dex-positive" : "dex-negative"}`}>
              {formatSgd(data.monthlySurplus)}
            </span>
          </div>
        </div>
        <div className="dex-score-badge" style={{ borderColor: scoreColor(data.overallScore) }}>
          <span className="dex-score-value" style={{ color: scoreColor(data.overallScore) }}>
            {data.overallScore}
          </span>
          <span className="dex-score-max">/100</span>
          <span className="dex-score-label">{data.onTrack ? "ON TRACK" : "KEEP GOING"}</span>
        </div>
      </header>

      <div className="dex-grid dex-grid-4">
        <Card title="Net Worth Summary" icon="💰">
          <Row label={`HDB Property (${Math.round(data.slices.find((s) => s.key === "hdb")?.pct ?? 0)}%)`} value={formatSgd(data.hdbValue)} />
          <Row label={`CPF (${Math.round(data.slices.find((s) => s.key === "cpf")?.pct ?? 0)}%)`} value={formatSgd(data.totalCpf)} />
          <Row
            label={`Investments & Insurance (${Math.round(data.slices.find((s) => s.key === "investments")?.pct ?? 0)}%)`}
            value={formatSgd(data.totalInvestments)}
          />
          <Row label="TOTAL NET WORTH" value={formatSgd(data.netWorth)} bold />
        </Card>

        <Card title="Asset Allocation" icon="📊">
          <div className="dex-donut-wrap">
            <div className="dex-donut">
              <Donut slices={data.slices} />
              <div className="dex-donut-hole">
                <span className="dex-donut-total">{formatSgd(data.netWorth)}</span>
                <span className="dex-donut-total-label">Total Assets</span>
              </div>
            </div>
            <div className="dex-legend">
              {data.slices.map((s) => (
                <div className="dex-legend-item" key={s.key}>
                  <span className="dex-legend-dot" style={{ background: SLICE_COLORS[s.key] }} />
                  {s.label} — {Math.round(s.pct)}%
                </div>
              ))}
            </div>
          </div>
        </Card>

        <Card title="CPF Accounts" icon="🏛️">
          <Row label="Ordinary Account (OA)" value={formatSgd(data.cpfOa)} />
          <Row label="MediSave (MA)" value={formatSgd(data.cpfMa)} />
          <Row label="Special / Retirement Acct (SA/RA)" value={formatSgd(data.cpfSaRa)} />
          <Row label="TOTAL CPF" value={formatSgd(data.totalCpf)} bold />
        </Card>

        <Card title="Monthly Cash Flow" icon="💵">
          {data.incomeItems.map((item) => (
            <Row key={item.id} label={item.label || "(unlabelled)"} value={formatSgd(item.amount)} />
          ))}
          <Row label="TOTAL INCOME" value={formatSgd(data.totalIncome)} bold />
          <Row label="Monthly expenses (see below)" value={formatSgd(data.totalExpenses)} muted />
          <Row label="Monthly liabilities (see below)" value={formatSgd(data.totalLiabilities)} muted />
          <Row
            label={data.monthlySurplus >= 0 ? "SURPLUS / MONTH" : "DEFICIT / MONTH"}
            value={formatSgd(Math.abs(data.monthlySurplus))}
            bold
          />
        </Card>
      </div>

      <div className="dex-grid dex-grid-4">
        <Card title="Investments & Insurance" icon="📈">
          {data.investmentItems.length === 0 ? (
            <p className="dex-empty">No investments or insurance holdings added yet.</p>
          ) : (
            <>
              {data.investmentItems.map((item) => (
                <Row key={item.id} label={item.label || "(unlabelled)"} value={formatSgd(item.amount)} />
              ))}
              <Row label="TOTAL" value={formatSgd(data.totalInvestments)} bold />
            </>
          )}
        </Card>

        <Card title="HDB Property Overview" icon="🏠">
          {data.hdbOverview ? (
            <>
              <Row label="Estimated sale value" value={formatSgd(data.hdbOverview.saleValue)} />
              <Row label="CPF principal used" value={formatSgd(data.hdbOverview.cpfPrincipalUsed)} />
              <Row label="CPF accrued interest" value={formatSgd(data.hdbOverview.cpfAccruedInterest)} />
              <Row label="CPF refund if sold today" value={formatSgd(data.hdbOverview.cpfRefund)} />
              <Row label="HDB loan outstanding" value={formatSgd(data.hdbOverview.loanOutstanding)} bold />
            </>
          ) : (
            <p className="dex-empty">Save your numbers in the HDB Sale Proceeds calculator to see this breakdown.</p>
          )}
        </Card>

        <Card title="Rightsizing Scenario" icon="🏘️">
          {data.rightsizing ? (
            <>
              <Row label="Estimated sale proceeds" value={formatSgd(data.rightsizing.saleProceeds)} />
              <Row label="Less: CPF refund" value={`-${formatSgd(data.rightsizing.cpfRefund)}`} />
              <Row label="Balance after CPF refund" value={formatSgd(data.rightsizing.balanceAfterCpfRefund)} />
              <Row label="Less: replacement flat" value={`-${formatSgd(data.rightsizing.replacementFlatPrice)}`} />
              <Row label="Less: legal & moving costs" value={`-${formatSgd(data.rightsizing.legalMovingCosts)}`} />
              <Row label="CASH RELEASED" value={formatSgd(data.rightsizing.cashReleased)} bold />
            </>
          ) : (
            <p className="dex-empty">Turn on "I'm considering downsizing" in the Selling Your HDB card to include this.</p>
          )}
        </Card>

        <Card title="Position After Rightsizing" icon="💼">
          {data.financialPositionAfter ? (
            <>
              <Row label="CPF savings" value={formatSgd(data.financialPositionAfter.cpfSavings)} />
              <Row label="Investments & insurance" value={formatSgd(data.financialPositionAfter.investmentsAndInsurance)} />
              <Row label="Cash released from rightsizing" value={formatSgd(data.financialPositionAfter.cashReleased)} />
              <Row label="ESTIMATED FINANCIAL ASSETS" value={formatSgd(data.financialPositionAfter.estimatedFinancialAssets)} bold />
            </>
          ) : (
            <p className="dex-empty">Available once a rightsizing scenario is set up.</p>
          )}
        </Card>
      </div>

      <div className="dex-grid dex-grid-3">
        <Card title="Expenses & Liabilities" icon="🧾">
          {data.expenseItems.length === 0 ? (
            <p className="dex-empty">No expenses added yet.</p>
          ) : (
            <>
              {data.expenseItems.map((item) => (
                <Row key={item.id} label={item.label || "(unlabelled)"} value={formatSgd(item.amount)} />
              ))}
              <Row label="TOTAL MONTHLY EXPENSES" value={formatSgd(data.totalExpenses)} bold />
            </>
          )}
          <div className="dex-subheading">Liabilities</div>
          {data.liabilityItems.filter((i) => i.amount > 0).length === 0 ? (
            <p className="dex-empty" style={{ marginTop: 10 }}>No liabilities added yet.</p>
          ) : (
            <>
              {data.liabilityItems
                .filter((i) => i.amount > 0)
                .map((item) => (
                  <Row key={item.id} label={item.label || "(unlabelled)"} value={formatSgd(item.amount)} />
                ))}
              <Row label="TOTAL MONTHLY LIABILITIES" value={formatSgd(data.totalLiabilities)} bold />
            </>
          )}
        </Card>

        <Card title="Retirement Health Check" icon="❤️">
          {data.healthDimensions.map((d) => (
            <div className="dex-bar-row" key={d.key}>
              <div className="dex-bar-label">
                <span>{d.label}</span>
                <span className="dex-bar-status" style={{ color: STATUS_DOT[d.status] }}>
                  {HEALTH_STATUS_LABEL[d.status]}
                </span>
              </div>
              <div className="dex-bar-track">
                <div
                  className="dex-bar-fill"
                  style={{ width: `${STATUS_SCORE[d.status] * 10}%`, background: STATUS_DOT[d.status] }}
                />
              </div>
            </div>
          ))}
          <div className="dex-overall-score">
            OVERALL SCORE <strong style={{ color: scoreColor(data.overallScore) }}>{data.overallScore}/100</strong>
          </div>
        </Card>

        <Card title="Retirement Timeline" icon="🗓️">
          <div className="dex-timeline">
            {data.timelineSteps.map((step, i) => (
              <div className="dex-timeline-step" key={i}>
                <div className="dex-timeline-dot">{step.icon}</div>
                <div className="dex-timeline-body">
                  <div className="dex-timeline-age">{step.age}</div>
                  <div className="dex-timeline-label">{step.label}</div>
                </div>
              </div>
            ))}
          </div>
        </Card>
      </div>

      <div className="dex-grid dex-grid-3 dex-footer">
        <div className="dex-footer-card">
          <h4>💡 What's working</h4>
          <ul>
            {strongPoints.length === 0 ? <li>Add more of your numbers to see insights here.</li> : strongPoints.map((d) => <li key={d.key}>{d.note}</li>)}
          </ul>
        </div>
        <div className="dex-footer-card">
          <h4>🎯 Worth a look</h4>
          <ul>
            {actionPoints.length === 0 ? <li>No action items — every dimension checks out.</li> : actionPoints.map((d) => <li key={d.key}>{d.note}</li>)}
          </ul>
        </div>
        <div className="dex-footer-card">
          <h4>📌 Notes</h4>
          <ul>
            <li>All figures are based only on what you've entered in SG Money — nothing is verified or fetched.</li>
            <li>This image is generated entirely in your browser — nothing is sent to a server.</li>
            <li>The health check is an illustrative self-check, not professional financial advice.</li>
          </ul>
        </div>
      </div>
    </div>
  );
}
